### ISSUE TITLE
Generator: Customize flat-world.

### ISSUE THREAD

**Issue by filfat** [JSPrismarine/JSPrismarine#253]
```yaml
worlds:
  world:
    generator: overworld
    seed: 1234
    layers:
      - minecraft:grass
      - minecraft:dirt
      - minecraft:dirt
      - minecraft:stone
      - minecraft:bedrock
```
